-- MySQL Script generated by MySQL Workbench
-- 12/10/15 11:18:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MalaysianPoliceApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MalaysianPoliceApp` ;

-- -----------------------------------------------------
-- Schema MalaysianPoliceApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MalaysianPoliceApp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MalaysianPoliceApp` ;

-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_USERS` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_USERS` (
  `username` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  `fullname` VARCHAR(200) NOT NULL COMMENT '',
  `age` TINYINT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_CASES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_CASES` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_CASES` (
  `id_number` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name_title` VARCHAR(100) NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `time` TIME NOT NULL COMMENT '',
  `geolocation` VARCHAR(100) NOT NULL COMMENT '',
  `officer_assigned` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id_number`)  COMMENT '',
  CONSTRAINT `fk_TB_CASES_TB_USERS1`
    FOREIGN KEY (`officer_assigned`)
    REFERENCES `MalaysianPoliceApp`.`TB_USERS` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_CASES_TB_USERS1_idx` ON `MalaysianPoliceApp`.`TB_CASES` (`officer_assigned` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_PERSON_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_PERSON_TYPE` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_PERSON_TYPE` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MalaysianPoliceApp`.`TB_PERSON_TYPE` (`name` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_ID_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_ID_TYPE` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_ID_TYPE` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MalaysianPoliceApp`.`TB_ID_TYPE` (`name` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_PERSONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_PERSONS` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_PERSONS` (
  `first_name` VARCHAR(50) NOT NULL COMMENT '',
  `last_name` VARCHAR(100) NOT NULL COMMENT '',
  `gender` VARCHAR(1) NOT NULL COMMENT '',
  `race` VARCHAR(20) NOT NULL COMMENT '',
  `id` VARCHAR(40) NOT NULL COMMENT '',
  `id_type` INT NOT NULL COMMENT '',
  `id_address` BLOB(800) NOT NULL COMMENT '',
  `person_type` INT NOT NULL COMMENT '',
  `notes` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_TB_PERSONS_TB_PERSON_TYPE1`
    FOREIGN KEY (`person_type`)
    REFERENCES `MalaysianPoliceApp`.`TB_PERSON_TYPE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PERSONS_TB_ID_TYPE1`
    FOREIGN KEY (`id_type`)
    REFERENCES `MalaysianPoliceApp`.`TB_ID_TYPE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_PERSONS_TB_PERSON_TYPE1_idx` ON `MalaysianPoliceApp`.`TB_PERSONS` (`person_type` ASC)  COMMENT '';

CREATE INDEX `fk_TB_PERSONS_TB_ID_TYPE1_idx` ON `MalaysianPoliceApp`.`TB_PERSONS` (`id_type` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_STATEMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_STATEMENTS` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_STATEMENTS` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `notes` BLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_TB_STATEMENTS_TB_CASES1`
    FOREIGN KEY (`case_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_CASES` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_STATEMENTS_TB_CASES1_idx` ON `MalaysianPoliceApp`.`TB_STATEMENTS` (`case_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_IO_LOGSHEET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_IO_LOGSHEET` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_IO_LOGSHEET` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `datetime` DATETIME NOT NULL COMMENT '',
  `starttime` DATETIME NOT NULL COMMENT '',
  `notes` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_TB_IO_LOGSHEET_TB_CASES1`
    FOREIGN KEY (`case_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_CASES` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_IO_LOGSHEET_TB_CASES1_idx` ON `MalaysianPoliceApp`.`TB_IO_LOGSHEET` (`case_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_EXHIBITS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_EXHIBITS` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_EXHIBITS` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `location` VARCHAR(100) NULL COMMENT '',
  `notes` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_TB_EXHIBITS_TB_CASES1`
    FOREIGN KEY (`case_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_CASES` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_EXHIBITS_TB_CASES1_idx` ON `MalaysianPoliceApp`.`TB_EXHIBITS` (`case_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_MULTIMEDIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_MULTIMEDIA` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_MULTIMEDIA` (
  `fullpath` VARCHAR(200) NOT NULL COMMENT 'The fullpath or URI to the file.',
  `type` INT NOT NULL COMMENT 'The type of multimedia file: audio, video, picture, etc.',
  `fk_io_logsheet_id` INT NULL COMMENT '',
  `fk_users_username` VARCHAR(100) NULL COMMENT '',
  `fk_exhibits_id` INT NULL COMMENT '',
  `fk_statements_id` DATETIME NULL COMMENT '',
  `fk_persons_id` VARCHAR(40) NULL COMMENT '',
  PRIMARY KEY (`fullpath`)  COMMENT '',
  CONSTRAINT `fk_TB_MULTIMEDIA_TB_IO_LOGSHEET1`
    FOREIGN KEY (`fk_io_logsheet_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_IO_LOGSHEET` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MULTIMEDIA_TB_USERS1`
    FOREIGN KEY (`fk_users_username`)
    REFERENCES `MalaysianPoliceApp`.`TB_USERS` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MULTIMEDIA_TB_EXHIBITS1`
    FOREIGN KEY (`fk_exhibits_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_EXHIBITS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MULTIMEDIA_TB_STATEMENTS1`
    FOREIGN KEY (`fk_statements_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_STATEMENTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MULTIMEDIA_TB_PERSONS1`
    FOREIGN KEY (`fk_persons_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_PERSONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_MULTIMEDIA_TB_IO_LOGSHEET1_idx` ON `MalaysianPoliceApp`.`TB_MULTIMEDIA` (`fk_io_logsheet_id` ASC)  COMMENT '';

CREATE INDEX `fk_TB_MULTIMEDIA_TB_USERS1_idx` ON `MalaysianPoliceApp`.`TB_MULTIMEDIA` (`fk_users_username` ASC)  COMMENT '';

CREATE INDEX `fk_TB_MULTIMEDIA_TB_EXHIBITS1_idx` ON `MalaysianPoliceApp`.`TB_MULTIMEDIA` (`fk_exhibits_id` ASC)  COMMENT '';

CREATE INDEX `fk_TB_MULTIMEDIA_TB_STATEMENTS1_idx` ON `MalaysianPoliceApp`.`TB_MULTIMEDIA` (`fk_statements_id` ASC)  COMMENT '';

CREATE INDEX `fk_TB_MULTIMEDIA_TB_PERSONS1_idx` ON `MalaysianPoliceApp`.`TB_MULTIMEDIA` (`fk_persons_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `MalaysianPoliceApp`.`TB_CASES_PERSONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MalaysianPoliceApp`.`TB_CASES_PERSONS` ;

CREATE TABLE IF NOT EXISTS `MalaysianPoliceApp`.`TB_CASES_PERSONS` (
  `case_id` INT NOT NULL COMMENT '',
  `person_id` VARCHAR(40) NOT NULL COMMENT '',
  PRIMARY KEY (`case_id`, `person_id`)  COMMENT '',
  CONSTRAINT `fk_TB_CASES_has_TB_PERSONS_TB_CASES1`
    FOREIGN KEY (`case_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_CASES` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_CASES_has_TB_PERSONS_TB_PERSONS1`
    FOREIGN KEY (`person_id`)
    REFERENCES `MalaysianPoliceApp`.`TB_PERSONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TB_CASES_has_TB_PERSONS_TB_PERSONS1_idx` ON `MalaysianPoliceApp`.`TB_CASES_PERSONS` (`person_id` ASC)  COMMENT '';

CREATE INDEX `fk_TB_CASES_has_TB_PERSONS_TB_CASES1_idx` ON `MalaysianPoliceApp`.`TB_CASES_PERSONS` (`case_id` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
